import { Service, Protocol, Category } from './types';

export const services: Service[] = [
  {
    id: 'pawr-link',
    name: 'pawr.link',
    slug: 'pawr-link',
    description: 'Link-in-bio solution that works for both humans and AI agents. Create curated agent profiles with x402 microtransactions.',
    url: 'https://www.pawr.link',
    protocol: 'x402',
    category: 'identity',
    priceText: '$9-$10',
    network: 'Base',
    agentUpvotes: 42,
    humanUpvotes: 128,
    submittedAt: '2026-02-10',
    verified: true,
  },
  {
    id: 'zerion-api',
    name: 'Zerion API',
    slug: 'zerion-api',
    description: 'Access real-time portfolio data, token prices, and blockchain analytics through Zerion’s developer API.',
    url: 'https://developers.zerion.io',
    protocol: 'x402',
    category: 'data',
    priceText: '$0.01/req',
    network: 'Base',
    agentUpvotes: 28,
    humanUpvotes: 89,
    submittedAt: '2026-01-22',
    verified: true,
  },
  {
    id: 'checkr',
    name: 'Checkr',
    slug: 'checkr',
    description: 'Real-time X/Twitter attention intelligence for Base chain tokens. Track what’s trending on CT with attention/price divergence signals.',
    url: 'https://checkr.xyz',
    protocol: 'x402',
    category: 'data',
    priceText: 'free tier',
    network: 'Base',
    agentUpvotes: 156,
    humanUpvotes: 342,
    submittedAt: '2026-02-05',
    verified: true,
  },
  {
    id: 'mercuryclaw',
    name: 'Mercuryclaw',
    slug: 'mercuryclaw',
    description: 'Crypto market data API with real-time pricing, orderbook depth, and trading volume for major exchanges.',
    url: 'https://mercuryclaw.xyz',
    protocol: 'x402',
    category: 'data',
    priceText: '$0.10/req',
    network: 'Base',
    agentUpvotes: 73,
    humanUpvotes: 156,
    submittedAt: '2026-02-14',
    verified: true,
  },
  {
    id: 'hyperbolic-gpu',
    name: 'Hyperbolic GPU',
    slug: 'hyperbolic-gpu',
    description: 'Affordable LLM inference and training on GPU clusters. Pay per token processed via x402 microtransactions.',
    url: 'https://hyperbolic.xyz',
    protocol: 'x402',
    category: 'ai-ml',
    priceText: 'varies',
    network: 'Base',
    agentUpvotes: 89,
    humanUpvotes: 67,
    submittedAt: '2026-02-20',
    verified: true,
  },
  {
    id: 'coingecko',
    name: 'CoinGecko',
    slug: 'coingecko',
    description: 'Comprehensive crypto market data including prices, volumes, exchange stats, and community metrics.',
    url: 'https://www.coingecko.com/en/api',
    protocol: 'mpp',
    category: 'data',
    priceText: 'varies',
    network: 'Tempo',
    agentUpvotes: 45,
    humanUpvotes: 178,
    submittedAt: '2026-01-15',
    verified: true,
  },
  {
    id: 'tangle-network',
    name: 'Tangle Network',
    slug: 'tangle-network',
    description: 'Decentralized messaging and data broadcasting protocol with low-cost message publishing.',
    url: 'https://tangle.network',
    protocol: 'x402',
    category: 'infra',
    priceText: 'varies',
    network: 'Base',
    agentUpvotes: 34,
    humanUpvotes: 56,
    submittedAt: '2026-02-01',
    verified: true,
  },
  {
    id: 'orthogonal-skills',
    name: 'Orthogonal Skills',
    slug: 'orthogonal-skills',
    description: 'AI agent skills marketplace for building autonomous capabilities. Pay per skill invocation.',
    url: 'https://orthogonalskills.ai',
    protocol: 'x402',
    category: 'ai-ml',
    priceText: 'varies',
    network: 'Base',
    agentUpvotes: 67,
    humanUpvotes: 23,
    submittedAt: '2026-02-18',
    verified: true,
  },
  {
    id: 'dtelecom-voice',
    name: 'dTelecom Voice',
    slug: 'dtelecom-voice',
    description: 'Decentralized voice communication API with low-latency audio streaming and AI transcription.',
    url: 'https://dtelecom.io',
    protocol: 'x402',
    category: 'ai-ml',
    priceText: 'varies',
    network: 'Base',
    agentUpvotes: 41,
    humanUpvotes: 38,
    submittedAt: '2026-02-22',
    verified: true,
  },
  {
    id: 'xona-orbit',
    name: 'xona Orbit',
    slug: 'xona-orbit',
    description: 'Solana-based real-time market data feed with sub-millisecond latency for high-frequency trading.',
    url: 'https://xona.com',
    protocol: 'x402',
    category: 'data',
    priceText: 'varies',
    network: 'Solana',
    agentUpvotes: 92,
    humanUpvotes: 84,
    submittedAt: '2026-02-08',
    verified: true,
  },
];

export const categories: Category[] = ['data', 'trading', 'ai-ml', 'identity', 'social', 'infra'];

export const categoryLabels: Record<Category, string> = {
  data: 'Data',
  trading: 'Trading',
  'ai-ml': 'AI/ML',
  identity: 'Identity',
  social: 'Social',
  infra: 'Infra',
};

export const protocols: Protocol[] = ['x402', 'mpp', 'acp', 'other'];
export const protocolLabels: Record<Protocol, string> = {
  x402: 'x402',
  mpp: 'MPP',
  acp: 'ACP',
  other: 'Other',
};
